using System.Text.Json;
using System.Text.Json.Serialization;
using Api;
using Api.Features.KlaviyoConsent;

var builder = WebApplication.CreateBuilder(args);

// Generated by Immediate.Handlers / Immediate.Apis from the assembly name "Api".
builder.Services.AddApiHandlers();

builder.Services.AddKlaviyoConsent(builder.Configuration);

// "email_unsubscribed" <-> ConsentChangeType.EmailUnsubscribed
builder.Services.ConfigureHttpJsonOptions(o =>
    o.SerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower))
);

var app = builder.Build();

// No app.UseHttpsRedirection(): Klaviyo refuses to follow redirects, and the tunnel
// terminates TLS and forwards plain HTTP to us. Handle HTTPS at the edge in deployed environments.

app.MapApiEndpoints();

app.Run();

public partial class Program;